### ISSUE TITLE
I want to create a simple eMemo

### ISSUE THREAD

**Issue by sakalgb** [groupdocs-free-consulting/projects#23]
Hi, 

I want to create a simple application using GroupDocs, it should be able to 
1. Load Word templates into a word editor.
2. Edit The word template as an editor. 
3. Present editted word template to another user in a readonly view. 
4. Allow comments to be captured on the word document. 
5. Accept or reject comments. 
6. Finalize document and convert to pdf. 

I need to be able to do all this using the REST API.

Thanks.

**Comment by atirtahirgroupdocs** [comment]
@sakalgb 

Please share following details:

- What is your preferred development environment (e.g. Java or .NET, PHP)?
- Will the Word document have comments already? The application must detect comments and pass them to user so he can accept or reject? 
- Finalize the document: Does that mean whatever was added/edited in step 2, save that and convert the file?
- Will the user that has read-only access can accept or reject the comments?

**Comment by sakalgb** [comment]
Hi Atir,

Thanks for your reply.

Let me explain a bit more about what we have in mind.

We want to use this with an application called Nintex K2. Nintex will handle the workflow and API interactions using the REST API.

I’m just trying to understand this:

  1.  How to install a local version of GroupDocs on a server.
  2.  How to embed the different GroupDocs controls for editing and viewing pages in an iFrame.
  3.  Interacting with the GroupDocs application via REST API.
  4.  Which APIs we need to use for our application. We need to:
     *   Present a template word document for a user to fill.
     *   Save word document once user is done editing.
     *   Present read-only copy of the word document to a reviewer to review and pass comments.
     *   Save comments to word document from reviewer
     *   Present editable word document with comments to the originating user once review is done.
     *   User can edit word document and accept or reject comments.
     *   Once user is done accepting or rejecting comments, save document and convert to PDF.

Please also see responses to your questions below.


Latte.

**Comment by atirtahirgroupdocs** [comment]
@sakalgb 

Thanks for the details.
Since, you are going to integrate the application with Nintex and you want to process all the GroupDocs functionalities through the REST API calls. Let me share what we can implement (from your use-case) and what are the limitations of using GroupDocs APIs.

> How to install a local version of GroupDocs on a server.

You just have to install the NuGet packages for the following GroupDocs APIs:

* GroupDocs.Viewer
* GroupDocs.Annotation
* GroupDocs.Conversion

> How to embed the different GroupDocs controls for editing and viewing pages in an iFrame.

All GroupDocs APIs are UI agnostic. We'll explain how they could be used for editing and viewing purpose in your case. 

> Interacting with the GroupDocs application via REST API.

You have to develop the REST APIs to bridge your existing application with this new .NET application (that will implement GroupDocs APIs) that you are planning to develop. 

> Present a template word document for a user to fill.
Save word document once user is done editing.

For this purpose, we can use [GroupDocs.Editor for .NET](https://docs.groupdocs.com/editor/net/). But the API has no built-in support of any cloud storage providers. You have to pass source file from the local storage and save it back to the local storage. The other way is utilize cloud storage provider's interfaces to obtain (download) a content of remote file to a stream, and to upload a content from a stream into the remote file on a cloud. For more details please have a look at this [thread](https://forum.groupdocs.com/t/document-editor/9167/3?u=atir_tahir). 
#### Basic Work Flow

* Pass the source file from your environment to the .NET app using the REST API
* Download the file in .NET app, convert it to stream and pass stream to GroupDocs.Editor
* GroupDocs.Editor will pass the file to a WYSIWYG-editor for editing purpose 
* Edit the document, save document back to stream and pass it back to your exiting application or simply pass the edited document to GroupDocs.Viewer within same application to generate previews

> Present read-only copy of the word document to a reviewer to review.

GroupDocs.Viewer in your .NET application will convert the source/Word file to one of the following formats (depending on your use-case) for rendering or preview purpose:
* Image
* HTML
* PDF format 

Send this output (Image, PDF or HTML) back to your existing application for preview purpose. Of course, Image or PDF formats will be read-only. Later, you can simply render Image or PDF using iframe in your existing application.

> and pass comments

This comment, is this some kind of annotation? The workaround we can purpose is [text field](https://docs.groupdocs.com/annotation/net/add-text-field-annotation/) annotation.

#### Basic Workflow

Once the document (Image or PDF generated using GroupDocs.Viewer for preview) is reviewed and user wants to comment it. You again have to pass the document (the actual source file e.g. Word) to .NET application using REST API (if it is not available in your .NET application). 
Later, in .NET application, source file must be passed to a custom developed UI using any JS framework and annotation can be added. 

> Save comments to word document from reviewer
Present editable word document with comments to the originating user once review is done.
Save comments to word document from reviewer

Once, text field annotation is added, it will be saved in Word document and you can send back this file to the existing application. As you have the annotated/commented document back in your application. You can show it to user using iframe. But to show the Word file in iframe, you again have to use GroupDocs.Viewer API (that will generate previews for you either Image or PDF formats).

> User can edit word document and accept or reject comments.

Now in order to manipulate the annotations/comments, you have to pass the source file to GroupDocs.Annotation in your .NET application using REST API.  And there, again .NET application will pass this document to some UI to remove annotations. 

> Once user is done accepting or rejecting comments, save document and convert to PDF.

Once annotations/comments manipulation is done, the source file could be passed to GroupDocs.Conversion in your .NET application. GroupDocs.Conversion will convert the Word file to PDF and pass it back to the existing application. 

Since, these APIs are UI-Agnostic, you have to develop all the front-end/UI using your own custom logic. For your ease, we already have MVC/WebForms applications for the above mentioned GroupDocs APIs.

1. [GroupDocs.Viewer](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/tree/master/Demos)
2. [GroupDocs.Annotation](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET/tree/master/Demos)
3. [GroupDocs.Conversion](https://github.com/groupdocs-conversion/GroupDocs.Conversion-for-.NET/tree/master/Demos)

1 takes a document as input and renders it in your browser. 2 takes a document and annotate it and saves it back. 3 takes a document (e.g. Word file) and converts it to PDF.

**Comment by sakalgb** [comment]
Hi Atir,

Thanks again for the detailed response.

How much hand-holding can you do for us on this as we have extremely limited experience working with code.

**Comment by atirtahirgroupdocs** [comment]
@sakalgb this scenario is under investigation. We are analyzing the requirements.  You'll be notified in case of any update.
